### ISSUE TITLE
For each ep_products (`clustered`) without `lca_product` match, select the most suitable sector.

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#362] opened 2023-05-29 16:42 UTC
In the [tr_companies_raw_v2](https://drive.google.com/drive/folders/15lJ7tfH0KRB4mU0us7XUTBvpuo3MzxRU) which is the foundation for all our indicators products are missing. This is due to the fact that we only consider those products that were matched to ecoinvent. For the rest the clustered column is NA. However, it would also be nice to display the other products in the overview file of all our companies that we would have based on clustered, so the pre-processed products from europages. The challenge is here that we don't know which sector they refer to as we only can derive the tilt_sector via mapping tilt_sectors with ecoinvent_categories. There might be some manual work included to decide which products comes from which sector. Or is there any way of pre-processing this automatically? The whole problem is also here described in a toy data set [here](https://docs.google.com/spreadsheets/d/1qmOH54ncF229r3OAn_5cEwtGBpV-FZ6V_Co7KNszN9o/edit#gid=1234975999). 

Please note that we could also do the whole process on product level, i.e. that we only match the clustered products via the company ID with europages_categories and then merge the tilt_sector and sub_sector to it... I am not quite sure which way is the best way. However, the problem I hope is clear and I am very much open for the way to find the solution!

@Tilmon to be able to do this task I think we need a file with all companies and their clustered products plus a column that indicates if we were able to match the clustered product to ecoinvent (as you have it with the tr_companies_raw_v2 data set). We then would need to map to those clustered products to all potential tilt sectors and subsectors through the categories_tilt_sector which can be found [here](https://docs.google.com/spreadsheets/d/1ZthIMGTtmN2iTmCUf3WeVyunfqdyf0doaKSPMDNJadc/edit#gid=0). Please have a look if this is the newest one.  Would be nice to understand through how many products we would need to go manually.

**Comment by AnneSchoenauer** [comment] 2023-05-29 16:43
@Tilmon could you please assign someone to this task when people are done with the PSTR/ISTR? This would be more important than the plots.

**Comment by Tilmon** [comment] 2023-05-30 11:56
Dear @MirijaHa and @ysherstyuk let's discuss in next week's sprint who's the best to take this over. The problem is in short the following: 

- we want to assign each `ep_product` to a `tilt_sector`. For those `ep_product `that you matched to a `lca_product `, that's easy because we get the sector from ecoinvent and can then map it to our tilt sectors via this mapper: https://docs.google.com/spreadsheets/d/1qmOH54ncF229r3OAn_5cEwtGBpV-FZ6V_Co7KNszN9o/edit#gid=0
- For those `ep_product `without match to `lca_product`, we need to find a workaround. We know for those `ep_products `only in which sectors the producing company is active (from Europages). So what we could do is: Use GPT to automatically select for each `ep_product `without `lca_product `match the most suitable sector per company. 
- Open for any other suggestion, but a way to go for it could be: train GPT 3 model with `ep_product `- `tilt_sector ` combinations that we already have and apply it to `ep_product ` without sector info.

**Comment by AnneSchoenauer** [comment] 2023-06-01 09:00
**Addition:**
Just to add on what is said previous. It seems to be that the sheet [tr_companies_raw_v2](https://drive.google.com/drive/folders/15lJ7tfH0KRB4mU0us7XUTBvpuo3MzxRU) already contains the information which tilt sector was mapped to a specific company (without knowing which product refers to it). For example in row 21 the company `07-schanksysteme-gmbh_00000005076936-001` has the following sector: `Other; Land Use` plus sub-sector: ``Other; Agriculture and Livestock; Food Related Products`. In that case there is one row with all the associated sectors to this company but as explained above the `products` are `NAs`. What we now would need to do is filling in the NAs (as we have the information on the products) and then associate the right sectors to it.

**Comment by AnneSchoenauer** [comment] 2023-06-02 11:16
The same is true for updated version of dataset, which can be found in the same folder under the name `tr_companies_all_230531`.

**Comment by Tilmon** [comment] 2023-06-07 13:58
BLOCKED until Tilman provides test dataset.

**Comment by MirijaHa** [comment] 2023-06-08 10:25
Dear @AnneSchoenauer  @Tilmon and @ysherstyuk,

here are some thoughts. Please correct me if I am wrong about any of the assumptions.

1. For the successfully matched cases we do not have a 1 to 1 ep_product to tilt_sector mapping. First of all we do the matching on the ep_product x ep_main_activity x ep_geo level. Secondly each such level might have >1 best match. In consequence we actually infer sectors on the ep_product x ep_main_activity x ep_geo x lca_product level. Is that correct? For that reason I would argue that also for the ep_products that could not be matched we need to obtain sectors on the ep_product x ep_main_activity x ep_geo, or is there a content reasons that justifies the inconsistency of finding the sector on ep_product level for ep_products we could not match to LCA?
2. There are reasons why we have no lca_product(s) for an ep_products. A: There were only *no_match* cases (possibly due to suboptimal preselection with BERT). B: There might be tiny bugs (e.g. trying to join strings with different encodings), that might have lead to losing a very small fraction of matches C: stuff I cannot think of right now. However none of these reasons are systematic. Using a very different approach now for finding sectors for unmatchable in comparison to matchable cases introduces a bias, is that acceptable?


Remarks:
- Likely I will not train a model (i.e. finetune), but instead use a prompt engineering approach for this one.
- I only need a list of products that are affected, no need to prepare any other data

Questions:
- is it an accepatable outcome that sector remains NA if gpt decides that there is no sector that makes sense or do we always use the best sector?
- in the ticket it says "the column", in the toy data there are 2 columns tilt_sector and tile_subsector, which one is needed in the end?

**Comment by AnneSchoenauer** [comment] 2023-06-09 10:33
@MirijaHa, Tilman and I were able to identify the problem. @Tilmon I summarised the discussion here again, to document what we discussed. 

*Explaination of the problem*
With the matching from ep_products to lca_products we try to find out the *carbon footprint* of an ep_product. For an carbon footprint of an ep_product it is important to understand where (geography) the company is located, and also which activity (main_activity), the company has, as production processes depend on location as well as on if you are trading an apple or if you are producing an apple. However, with sectors, I would argue it doesn't depend on your location and activity. If a company has the product apple in its sortiment, the company should always be classified into the sector: "land_use/food" sector regardless of its location and its main_activity. That means categorising a product to a sector is different from the matching of a product to a carbon-footprint and therefore, shouldn't take the same approach.

*Reason for my approach*
Therefore, if we have the product "apple", I think it would be best to select all potential subsectors from all companies that have the product "apple" regardless of their location and geography in their sortiment. This means not to have one company_id (in my toy data I didn't use the company_id) but to have all potential subsectors from all companies, that have an apple in their sortiment and then let GPT decide which one of those potential subsector is the best match.

*Tilman's argument*
However, Tilman now said that selecting companies based on their main activity and geography shouldn't make a difference. And if it does we would see inconsistency in the europages data. To specify,  also with Mirja's approach two companies (company A, product: apple, main activity: production, geography: Germany and company B, product: apple, main activity: distributor, geography: France) should both be allocated to the sector "land use" and sub-sector "food". He said it would be interesting to see if this is really the case and if its not to discover the inconsistency in the ep_database.

*Decision*
We try your approach Mirja with selecting the companies based on their geography and main activity. However, it would be great if you could do a report afterwards with showing us all products and their sector and sub-sector. If an apple was allocated to a "land use" and "food" once and then the other time to "steel", that would be wrong. Tilman says it would be good to see this inconsistencies. So this is why we decided to take your approach.

**Comment by MirijaHa** [comment] 2023-06-09 12:16
Addendum: try  both lowest granularity ep_prod and ep_prod x geo x man_act on 100 products first

**Comment by MirijaHa** [comment] 2023-06-29 09:04
Addendum: For terms that were matched to an lca_product in isic_sectors for which thee is no mappin tilt_sector also use the new approach.

**Comment by MirijaHa** [comment] 2023-06-29 09:05
Addendum: The same applies to lca_products in isic_sector "not_available"

**Comment by AnneSchoenauer** [comment] 2023-10-17 12:07
@bobresink and @kalashsinghal is this done?

**Comment by bobresink** [comment] 2023-10-17 12:20
This is the sector resolving approach that Mirja worked on, so it is done.

**Closed** 2023-11-07 08:14 UTC
Labels: question
